# Use the official .NET SDK image to build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copy csproj and restore
COPY *.sln .
COPY Sale.API/*.csproj ./Sale.API/
COPY Sale.BAL/*.csproj ./Sale.BAL/
COPY Sale.DAL/*.csproj ./Sale.DAL/
COPY Sale.Models/*.csproj ./Sale.Models/

RUN dotnet restore Sale.API/Sale.API.csproj

# Copy all files and publish
COPY . .
WORKDIR /app/Sale.API
RUN dotnet publish -c Release -o /app/out

# Runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/out .
EXPOSE 8080
ENTRYPOINT ["dotnet", "Sale.API.dll"]
